stages:
  - build
  - test
  - deploy

job:build:
  stage: build
  image: python:3.7
  script:
    - apt-get update -q -y
    - pip install -r requirements.txt

job:test:
  stage: test
  script:
    - pytest -s --cov=nba_scraper test.py
    - coverage run test.py 

