language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"      # current detault Python on Travis CI
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
# command to run tests
script:
  - pytest -s --cov=nba_scraper test.py
  - coverage run test.py 

after_success:
    - codecov -t b894e205-3940-45ce-961d-fb78ce0f1f9f